Nomor 1

In [13]:
import numpy as np

In [14]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[2, 4, 6], [3, 5, 7]])
print("Matrix X:\n", (X))

Matrix X:
 [[2 4 6]
 [3 5 7]]


In [15]:
# tampilkan ukuran dari matrix X
print("Ukuran matrix X:", X.shape)

Ukuran matrix X: (2, 3)


In [16]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
print("Elemen kolom pertama dari matrix X:", X[:,0])

Elemen kolom pertama dari matrix X: [2 3]


In [17]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
print("Elemen baris kedua dari matrix X:", X[1,:])

Elemen baris kedua dari matrix X: [3 5 7]


Nomor 2

Ulangi soal nomor 1 menggunakan pytorch

In [1]:
import torch as pt

In [2]:
# buat matrix X berukuran 2x3 menggunakan torch
X_pt = pt.tensor([[2, 4, 6], [3, 5, 7]])
print("Matrix X_pt:\n", X_pt)

Matrix X_pt:
 tensor([[2, 4, 6],
        [3, 5, 7]])


In [3]:
# tampilkan ukuran dari matrix X_pt
print("Ukuran matrix X_pt:", X_pt.shape)

Ukuran matrix X_pt: torch.Size([2, 3])


In [4]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_pt
print("Elemen kolom pertama dari matrix X_pt:", X_pt[:,0])

Elemen kolom pertama dari matrix X_pt: tensor([2, 3])


In [5]:
#tampilkan seluruh elemen dari baris kedua dari matrix X_pt
print("Elemen baris kedua dari matrix X_pt:", X_pt[1,:])

Elemen baris kedua dari matrix X_pt: tensor([3, 5, 7])


Ulangi soal nomor 1 menggunakan tensorflow

In [6]:
import tensorflow as tf

In [7]:
# buat matrix X berukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[2, 4, 6], [3, 5, 7]])
print("Matrix X_tf:\n", X_tf)

Matrix X_tf:
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 4, 6],
       [3, 5, 7]], dtype=int32)>


In [9]:
# tampilkan ukuran dari matrix X_tf
print("Ukuran dari matrix X_tf:", tf.shape(X_tf))

Ukuran dari matrix X_tf: tf.Tensor([2 3], shape=(2,), dtype=int32)


In [10]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
print("Elemen kolom pertama dari matrix X_tf:", X_tf[:,0])

Elemen kolom pertama dari matrix X_tf: tf.Tensor([2 3], shape=(2,), dtype=int32)


In [11]:
#tampilkan seluruh elemen dari baris kedua dari matrix X_tf
print("Elemen baris kedua dari matrix X_tf:", X_tf[1,:])

Elemen baris kedua dari matrix X_tf: tf.Tensor([3 5 7], shape=(3,), dtype=int32)
