Nomor 1

In [1]:
import numpy as np

In [2]:
# buat vector x dengan ukuran 3x1
x = np.array([[1], [2], [3]])
print("Vektor x:\n", x)

Vektor x:
 [[1]
 [2]
 [3]]


In [3]:
# hitung panjang vector x
print("Panjang vektor x:", len(x))

Panjang vektor x: 3


In [4]:
# tampilkan ukuran vector x
print("Ukuran vektor x:", x.shape)

Ukuran vektor x: (3, 1)


In [ ]:
# tampilkan tipe data dari vector x
print("Tipe data vektor x:", type(x))

Tipe data vektor x: <class 'numpy.ndarray'>


In [ ]:
# akses elemen pertama dari vector x
print("Elemen pertama vektor x:", x[0])

Elemen pertama vektor x: [1]


In [ ]:
# tampilkan tipe data elemen pertama dari vector x
print("Tipe data elemen pertama vektor x:", type(x[0]))

Tipe data elemen pertama vektor x: <class 'numpy.ndarray'>


Nomor 2

In [6]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
print("vektor x_t:\n", x_t)

vektor x_t:
 [[1 2 3]]


In [8]:
# tampilkan ukuran dari vector x_t
print("ukuran vektor x_t:", x_t.shape)

ukuran vektor x_t: (1, 3)


In [9]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[12, 14, 16]])
y_t = y.T
print("vektor y_t:\n", y_t)

vektor y_t:
 [[12]
 [14]
 [16]]


In [10]:
# tampilkan ukuran dari vector y_t
print("ukuran vektor y_t:", y_t.shape)

ukuran vektor y_t: (3, 1)


Nomor 3

Lakukan soal nomor 2 menggunakan pytorch

In [11]:
import torch

In [12]:
# lakukan transpose pada vector x dan simpan pada variabel x_pt
x_pt = torch.tensor([[1], [2], [3]])
x_pt = x.T
print("vektor x_pt:\n", x_pt)

vektor x_pt:
 [[1 2 3]]


In [13]:
# tampilkan ukuran dari vector x_pt
print("ukuran vektor x_pt:", x_pt.shape)

ukuran vektor x_pt: (1, 3)


In [14]:
# lakukan transpose pada vector y dan simpan pada variabel y_pt
y_pt = torch.tensor(y)
y_pt = y_pt.T
print("vektor y_pt:\n", y_pt)

vektor y_pt:
 tensor([[12],
        [14],
        [16]])


In [15]:
# tampilkan ukuran dari vector y_pt
print("ukuran vektor y_pt:", y_pt.shape)

ukuran vektor y_pt: torch.Size([3, 1])


Lakukan soal nomor 2 menggunakan tensorflow

In [16]:
import tensorflow as tf

In [17]:
# lakukan transpose pada vector x dan simpan pada variabel x_tf
x_tf = tf.constant([[1],
                   [2],
                   [3]])
x_tf = x.T
print("vektor x_tf:\n", x_tf)

vektor x_tf:
 [[1 2 3]]


In [18]:
# tampilkan ukuran dari vector x_tf
print("ukuran vektor x_tf:", x_tf.shape)

ukuran vektor x_tf: (1, 3)


In [19]:
# lakukan transpose pada vector y dan simpan pada variabel y_tf
y_tf = tf.Variable([12, 14, 16])
y_tf = y.T
print("vektor y_tf:\n", y_tf)

vektor y_tf:
 [[12]
 [14]
 [16]]


In [20]:
# tampilkan ukuran dari vector y_tf
print("ukuran vektor y_tf:", y_tf.shape)

ukuran vektor y_tf: (3, 1)
