Nomor 1


In [7]:
import numpy as np
import torch as pt
import tensorflow as tf

In [8]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[10, 20, 30], [15, 20, 45]])
print(X)

[[10 20 30]
 [15 20 45]]


In [9]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = pt.tensor([[10, 20, 30], [15, 30, 45]])
print(X_pt)

tensor([[10, 20, 30],
        [15, 30, 45]])


In [10]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[10, 20, 30], [15, 30, 45]])
print(X_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [15, 30, 45]], dtype=int32)>


In [11]:
# lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar
print(X * 2)
print("\n", X_pt * 2)
print("\n", X_tf * 2)

[[20 40 60]
 [30 40 90]]

 tensor([[20, 40, 60],
        [30, 60, 90]])

 tf.Tensor(
[[20 40 60]
 [30 60 90]], shape=(2, 3), dtype=int32)


In [12]:
# lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar
print(X + 10)
print("\n", X_pt + 10)
print("\n", X_tf + 10)

[[20 30 40]
 [25 30 55]]

 tensor([[20, 30, 40],
        [25, 40, 55]])

 tf.Tensor(
[[20 30 40]
 [25 40 55]], shape=(2, 3), dtype=int32)


In [13]:
# lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
print(X - 5)
print("\n", X_pt - 5)
print("\n", X_tf - 5)

[[ 5 15 25]
 [10 15 40]]

 tensor([[ 5, 15, 25],
        [10, 25, 40]])

 tf.Tensor(
[[ 5 15 25]
 [10 25 40]], shape=(2, 3), dtype=int32)


Nomor 2

In [14]:
# buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y = np.array([[20, 40, 50], [30, 60, 90]])
print(Y)

[[20 40 50]
 [30 60 90]]


In [15]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = pt.tensor([[20, 30, 40], [30, 60, 90]])
print(Y_pt)

tensor([[20, 30, 40],
        [30, 60, 90]])


In [16]:
# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable([[20, 30, 40], [30, 60, 90]])
print(Y_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[20, 30, 40],
       [30, 60, 90]], dtype=int32)>


In [17]:
# kalikan matrix X dengan Y
print(X * Y)

[[ 200  800 1500]
 [ 450 1200 4050]]


In [18]:
# kalikan matrix X_pt dengan Y_pt
print(X_pt * Y_pt)

tensor([[ 200,  600, 1200],
        [ 450, 1800, 4050]])


In [19]:
# kalikan matrix X_tf dengan Y_tf
print(X_tf * Y_tf)

tf.Tensor(
[[ 200  600 1200]
 [ 450 1800 4050]], shape=(2, 3), dtype=int32)
