Nomor 1


In [3]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
import numpy as np

X = np.array([[10, 20, 30], [15, 30, 45]])
print("Matrix X:\n", X)

Matrix X:
 [[10 20 30]
 [15 30 45]]


In [4]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
import torch as pt

X_pt = pt.tensor([[10, 20, 30], [15, 30, 45]])
print("Matrix X_pt:\n", X_pt)

Matrix X_pt:
 tensor([[10, 20, 30],
        [15, 30, 45]])


In [5]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
import tensorflow as tf

X_tf = tf.Variable([[10, 20, 30], [15, 30, 45]])
print("Matrix X_tf:\n", X_tf)

Matrix X_tf:
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [15, 30, 45]], dtype=int32)>


Nomor 2

In [7]:
# lakukan transpose pada matrix X
X_trans = X.T
print("Transpose matrix X:\n", X_trans)

# lakukan transpose pada matrix X_pt
X_pt_trans = X_pt.T
print("\nTranspose matrix X_pt:\n", X_pt_trans)

# lakukan transpose pada matrix X_tf
X_tf_trans = tf.transpose(X_tf)
print("\nTranspose matrix X_tf:\n", X_tf_trans)

Transpose matrix X:
 [[10 15]
 [20 30]
 [30 45]]

Transpose matrix X_pt:
 tensor([[10, 15],
        [20, 30],
        [30, 45]])

Transpose matrix X_tf:
 tf.Tensor(
[[10 15]
 [20 30]
 [30 45]], shape=(3, 2), dtype=int32)
