In [1]:
import numpy as np
import torch as pt
import tensorflow as tf

Nomor 1

In [2]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[10, 20, 30], [15, 30, 45]])
print(X)

[[10 20 30]
 [15 30 45]]


In [3]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
print(X.sum())

150


In [4]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[10, 20, 30], [15, 30, 45]])
print(X_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [15, 30, 45]], dtype=int32)>


In [5]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = pt.tensor([[10, 20, 30], [15, 30, 45]])
print(X_pt)

tensor([[10, 20, 30],
        [15, 30, 45]])


Nomor 2

In [6]:
# hitung hasil penjumlahan seluruh elemen matrix X
print(X.sum())

150


In [7]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt
print(pt.sum(X_pt))

tensor(150)


In [8]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf
print(tf.reduce_sum(X_tf))

tf.Tensor(150, shape=(), dtype=int32)


Nomor 3

In [9]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
print(np.sum(X, axis=1))

[60 90]


In [10]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
print(pt.sum(X_pt, axis=1))

tensor([60, 90])


In [11]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
print(tf.reduce_sum(X_tf, axis=1))

tf.Tensor([60 90], shape=(2,), dtype=int32)


Nomor 4

In [12]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
print(np.sum(X, axis=0))

[25 50 75]


In [13]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
print(pt.sum(X_pt, axis=0))

tensor([25, 50, 75])


In [14]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
print(tf.reduce_sum(X_tf, axis=0))

tf.Tensor([25 50 75], shape=(3,), dtype=int32)


Nomor 5

In [15]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf
X_min = np.min(X)
X_pt_min = pt.min(X_pt)
X_tf_min = tf.reduce_min(X_tf)
print(f"Nilai minimal dari X Adalah : {X_min}")
print(f"Nilai minimal dari X_pt Adalah : {X_pt_min}")
print(f"Nilai minimal dari X_tf Adalah : {X_tf_min.numpy()}")

Nilai minimal dari X Adalah : 10
Nilai minimal dari X_pt Adalah : 10
Nilai minimal dari X_tf Adalah : 10


In [16]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf
X_max = np.max(X)
X_pt_max = pt.max(X_pt)
X_tf_max = tf.reduce_max(X_tf)
print(f"Nilai maksimal dari X Adalah : {X_max}")
print(f"Nilai maksimal dari X_pt Adalah : {X_pt_max}")
print(f"Nilai maksimal dari X_tf Adalah : {X_tf_max.numpy()}")

Nilai maksimal dari X Adalah : 45
Nilai maksimal dari X_pt Adalah : 45
Nilai maksimal dari X_tf Adalah : 45


In [17]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf
X_pt = X_pt.float()
X_mean = np.mean(X)
X_pt_mean = pt.mean(X_pt)
X_tf_mean = tf.reduce_mean(X_tf)
print(f"Nilai Rata-Rata dari X Adalah : {X_mean}")
print(f"Nilai Rata-Rata dari X_pt Adalah : {X_pt_mean}")
print(f"Nilai Rata-Rata dari X_tf Adalah : {X_tf_mean.numpy()}")

Nilai Rata-Rata dari X Adalah : 25.0
Nilai Rata-Rata dari X_pt Adalah : 25.0
Nilai Rata-Rata dari X_tf Adalah : 25


Nomor 6

In [20]:
# hitung hasil perkalian seluruh elemen matrix X
print(X.prod())

121500000


In [18]:
# hitung hasil perkalian seluruh elemen matrix X_pt
print(pt.prod(X_pt))

tensor(1.2150e+08)


In [19]:
# hitung hasil perkalian seluruh elemen matrix X_tf
print(tf.reduce_prod(X_tf))

tf.Tensor(121500000, shape=(), dtype=int32)
