Menggunakan numpy, pytorch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm

In [ ]:
# Dengan numpy
import numpy as np
X = np.array([[5, 10, 15], [10, 20, 30], [15, 30, 45]])
print("Matrix X:\n", X)
print("Nilai frobenius norm matrix X: ",np.linalg.norm(X))

Matrix X:
 [[ 5 10 15]
 [10 20 30]
 [15 30 45]]
Nilai frobenius norm matrix X:  70.0


In [ ]:
# Dengan pytorch
import torch as pt
X_pt = pt.tensor([[5, 10, 15], [10, 20, 30], [15, 30, 45]]).float()
print("Matrix X_pt:\n", X_pt)
print("Nilai frobenius norm matrix X_pt: ",pt.norm(X_pt))

Matrix X_pt:
 tensor([[ 5., 10., 15.],
        [10., 20., 30.],
        [15., 30., 45.]])
Nilai frobenius norm matrix X_pt:  tensor(70.)


In [16]:
# Dengan tensorflow
import tensorflow as tf
X_tf = tf.Variable([[5, 10, 15], [10, 20, 30], [15, 30, 45]], dtype=tf.float32)
print("Matrix X_tf:\n", X_tf)
print("Nilai frobenius norm matrix X_tf: ", tf.norm(X_tf))

Matrix X_tf:
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 5., 10., 15.],
       [10., 20., 30.],
       [15., 30., 45.]], dtype=float32)>
Nilai frobenius norm matrix X_tf:  tf.Tensor(70.0, shape=(), dtype=float32)
