Nomor 1

In [1]:
# buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
import numpy as np
A = np.array([[10, 20, 30], [15, 30, 45]])
print("Matrix A: \n",A)
b = np.array([[1], [2], [3]])
print("\nVector b: \n",b)

Matrix A: 
 [[10 20 30]
 [15 30 45]]

Vector b: 
 [[1]
 [2]
 [3]]


In [2]:
# buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
import torch as pt
A_pt = pt.tensor([[10, 20, 30], [15, 30, 45]])
print("Matrix A: \n",A_pt)
b_pt = pt.tensor([[1], [2], [3]])
print("\nVector b: \n",b_pt)

Matrix A: 
 tensor([[10, 20, 30],
        [15, 30, 45]])

Vector b: 
 tensor([[1],
        [2],
        [3]])


In [3]:
# buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
import tensorflow as tf
A_tf = tf.Variable([[10, 20, 30], [15, 30, 45]])
print("Matrix A: \n",A_tf)
b_tf = tf.Variable([[1], [2], [3]])
print("\nVector b: \n",b_tf)

Matrix A: 
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [15, 30, 45]], dtype=int32)>

Vector b: 
 <tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>


Nomor 2

In [4]:
# tampilkan ukuran matrix A dan vector b
print("Ukuran Matrix A: ",A.shape)
print("Ukuran Vector b: ",b.shape)

Ukuran Matrix A:  (2, 3)
Ukuran Vector b:  (3, 1)


Nomor 3

In [5]:
# kalikan matrix A dengan vector b
print("Hasil kalikan matrix A dengan vector b: \n",np.dot(A, b))

Hasil kalikan matrix A dengan vector b: 
 [[140]
 [210]]


In [6]:
# kalikan matrix A_pt dengan vector b_pt
print("Hasil kalikan matriks A_pt dengan vector b_pt: \n",pt.matmul(A_pt, b_pt))

Hasil kalikan matriks A_pt dengan vector b_pt: 
 tensor([[140],
        [210]])


In [14]:
# kalikan matrix A_tf dengan vector b_tf
print("Hasil kalikan matriks A_tf dengan vector b_tf: \n",tf.matmul(A_tf, b_tf))

Hasil kalikan matriks A_tf dengan vector b_tf: 
 tf.Tensor(
[[140]
 [210]], shape=(2, 1), dtype=int32)


Nomor 4

In [8]:
# buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix B: \n",B)

Matrix B: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = pt.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix B_pt: \n",B_pt)

Matrix B_pt: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [10]:
# buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix B_tf: \n",B_tf)

Matrix B_tf: 
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>


Nomor 5

In [11]:
# kalikan matrix A dengan matrix B
print("Hasil kalikan matrix A dengan matrix B: \n",np.dot(A, B))

Hasil kalikan matrix A dengan matrix B: 
 [[300 360 420]
 [450 540 630]]


In [12]:
# kalikan matrix A_pt dengan matrix B_pt
print("Hasil kalikan matrix A_pt dengan matrix B_pt: \n",pt.matmul(A_pt, B_pt))

Hasil kalikan matrix A_pt dengan matrix B_pt: 
 tensor([[300, 360, 420],
        [450, 540, 630]])


In [15]:
# kalikan matrix A_tf dengan matrix B_tf
print("Hasil kalikan matrix A_tf dengan matrix B_tf: \n",tf.matmul(A_tf, B_tf))

Hasil kalikan matrix A_tf dengan matrix B_tf: 
 tf.Tensor(
[[300 360 420]
 [450 540 630]], shape=(2, 3), dtype=int32)


Nomor 6

In [25]:
# buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
print("Hasil kalikan matrix A dengan matrix B: \n",np.dot(A, B))
try:
    print("Hasil kalikan matrix B dengan matrix A: \n",np.dot(B, A))
except ValueError as e:
    print("\nBA tidak bisa dihitung:")
    print(e)
'''Perkalian matriks tidak bersifat komutatif (AB ≠ BA), karena:
1. Tidak semua pasangan matriks dapat dikalikan dalam kedua urutan (AB bisa tetapi BA tidak, atau sebaliknya)
2. Meskipun kedua perkalian terdefinisi, hasilnya belum tentu sama)'''

Hasil kalikan matrix A dengan matrix B: 
 [[300 360 420]
 [450 540 630]]

BA tidak bisa dihitung:
shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)


'Perkalian matriks tidak bersifat komutatif (AB ≠ BA), karena:\n1. Tidak semua pasangan matriks dapat dikalikan dalam kedua urutan (AB bisa tetapi BA tidak, atau sebaliknya) \n2. Meskipun kedua perkalian terdefinisi, hasilnya belum tentu sama)'