Nomor 1

In [7]:
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
import numpy as np
X_sym = np.array([[7, 1, 4], [1, 5, 2], [4, 2, 9]])
print("Matrix X_sym:\n", X_sym)
print("\nHasil transpose matrix X_sym:\n", X_sym.T)
print("\nBukti bahwa matrix X_sym adalah matrix simetris:\n", X_sym.T == X_sym)

Matrix X_sym:
 [[7 1 4]
 [1 5 2]
 [4 2 9]]

Hasil transpose matrix X_sym:
 [[7 1 4]
 [1 5 2]
 [4 2 9]]

Bukti bahwa matrix X_sym adalah matrix simetris:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Nomor 2

In [12]:
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
import torch as pt
I = pt.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
print("Matrix identitas 4x4:\n", I)

Matrix identitas 4x4:
 tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])


In [14]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
b_pt = pt.tensor([[10], [20], [30], [40]])
print("Vector b_pt:\n", b_pt)

Vector b_pt:
 tensor([[10],
        [20],
        [30],
        [40]])


In [18]:
# kalikan matrix I dengan vector b_pt
print("Hasil kali matrix I dengan vector b_pt:\n", pt.matmul(I, b_pt))

Hasil kali matrix I dengan vector b_pt:
 tensor([[10],
        [20],
        [30],
        [40]])
